Repository im-d-team/Dev-Docs, pull requests merged in 2019-09, with the labels that each got.

#60 페이징과 세그먼테이션.md
  CS/페이징과 세그먼테이션.md
  assets/images/coalescing.png
  assets/images/compaction.png
  assets/images/page_pageframe.png
  assets/images/segmentation.png
Labels: approval + 2, needs author response

#63 웹 브라우저의 작동원리
  Browser/웹 브라우저의 작동 원리.md
  README.md
Labels: approval + 2, needs review

#67 bind() 메소드
  Javascript/bind.md
Labels: approval + 2, needs review

#68 함수형 프로그래밍
  Language/함수형 프로그래밍.md
Labels: approval + 2, needs review

#70 Build Tool
  Javascript/Build Tool.md
Labels: approval + 2, needs review

#72 고차함수(High Order Function)
  Language/고차함수(High Order Function).md
Labels: approval + 2, needs review

#69 REST
  Network/REST.md
Labels: approval + 2, needs author response

#74 객체
  Javascript/object.md
Labels: approval + 2, needs author response

#76 Reactive
  Language/Reactive.md
Labels: approval + 2, needs review

#82 Change .mergify rule (delete branch rule)
  .mergify.yml
Labels: needs review

#73 Event Delegation
  Javascript/Event Delegation.md
Labels: approval + 2, needs review

#78 Reflow Repaint
  Performance/Reflow Repaint.md
Labels: approval + 2, needs review

#71 Currying
  Language/Currying.md
Labels: approval + 2, needs review
