Repository im-d-team/Dev-Docs, pull requests merged in 2019-05, with the labels that each got.

#3 Tricks of javascript
  Javascript/tricks_of_js.md
Labels: approval + 2

#10 함수 선언
  Javascript/함수 선언.md
Labels: approval + 2, needs author response, needs review

#8 input태그의 value바꾸기(input태그의 dirty flag).md
  HTML/input태그의_value바꾸기(input태그의_dirty flag).md
Labels: approval + 2, needs review

#9 웹접근성 ARIA
  HTML/ARIA.md
Labels: approval + 2, needs author response, needs review

#7 React의 컴포넌트 간의 Composition
  React/Composition.md
Labels: approval + 2

#14 props와 state
  HTML/input태그의_value바꾸기(input태그의_dirty flag).md
  README.md
  React/props와 state.md
Labels: approval + 2
