Repository im-d-team/Dev-Docs, pull requests merged in 2019-11, with the labels that each got.

#83 기본적인 렌더링 최적화 방법
  Performance/기본적인 렌더링 최적화 방법.md
  assets/TEST/bigfile.html
  assets/TEST/img_css_image_sprites.png
Labels: approval + 2, needs review

#88 Virtual Dom
  Network/JSend.md
  React/Virtual DOM.md
Labels: approval + 2, needs author response

#92 JSend
  Network/JSend.md
Labels: needs author response

#75 이벤트 루프(Event Loop)
  Javascript/이벤트 루프(Event Loop).md
  assets/images/event_loop.jpeg
  assets/images/event_loop_gif.gif
Labels: approval + 2, needs author response
