Repository im-d-team/Dev-Docs, pull requests merged in 2020-07, with the labels that each got.

#141 [네트워크 기초] Subnetmask
  Network/Subnetmask.md
Labels: approval + 3, needs review

#132 Composite
  Design_Pattern/Composite.md
Labels: Refactoring, approval + 3, needs review

#138 단일책임원칙
  CS/cohension&coupling.md
  CS/soc.md
  CS/srp.md
Labels: approval + 3, needs review

#143 개방 폐쇄 원칙
  CS/open-closed-principle.md
Labels: approval + 3, needs author response

#148 [네트워크 기초] Types of IP
  Network/TypesOfIP.md
Labels: approval + 3, needs author response

#140 JS - Scope
  Javascript/Scope.md
Labels: approval + 3, needs review

#149 Closure
  Javascript/Closure.md
Labels: approval + 3, needs review
