Repository im-d-team/Dev-Docs, pull requests merged in 2020-03, with the labels that each got.

#113 웹으로 모바일 레이아웃 만들기
  CSS/WebToMobile.md
  assets/gif/MobileCSS.gif
  assets/gif/MobileDock.gif
  assets/gif/MobileLayout.gif
Labels: approval + 2, needs review

#107 SQL Injection
  Security/SQL_Injection.md
  assets/images/SQL_Injection_1.png
  assets/images/SQL_Injection_2.png
Labels: approval + 2, needs review

#102 점진적향상, 우아한하향
  Deprecated/점진적향상_우아한하향.md
  Performance/점진적향상_우아한하향.md
Labels: approval + 2, needs review

#101 Web Worker
  Browser/WebWorker.md
  Deprecated/WebWorker.md
  README.md
Labels: approval + 2, needs review

#112 HTTP vs WebSocket
  Network/HTTP vs WebSocket.md
Labels: approval + 2, needs review

#110 Update Chrome 80 DevTool
  Tool/Chrome_80_DevTool.md
Labels: approval + 3, needs author response

#93 비선형 구조의 탐색
  CS/non-linear-search.md
  assets/images/non-linear-search-bfs.png
  assets/images/non-linear-search-dfs.png
  assets/images/non-linear-search.gif
Labels: approval + 2, needs review

#114 계수 정렬
  CS/Counting-sort.md
Labels: approval + 3, needs review
